import json
import re

json_path = r"C:\Users\Gonzi\Documents\Proyectos\gym-app\src\db\scraped_exercises_es.json"
out_path = r"C:\Users\Gonzi\.gemini\antigravity\brain\1931095c-6edd-45aa-85d5-baec766db84e\scraped_exercises_es_modified.json"

# Mapeo consolidado absoluto de todos los ejercicios sospechosos y adaptaciones de internet (Gimnasio)
mapeo_consolidado = {
    # CARDIO
    "treadmill running": "Cinta de correr",
    "treadmill walking": "Caminadora / Caminata en cinta",
    "stair climber": "Escaladora (Stair Climber)",
    "elliptical trainer": "Elíptica",
    "stationary bicycle": "Bicicleta estática",
    "jump rope": "Salto de cuerda",
    "rowing machine": "Máquina de remo",
    "run in place": "Trotar en el sitio",
    "burpee": "Burpee",
    "burpees": "Burpees",
    "jumping jacks": "Saltos de tijera (Jumping Jacks)",
    "mountain climber": "Escaladores (Mountain Climbers)",
    "high knees": "Elevación de rodillas (High Knees)",
    "squat jump": "Sentadilla con salto",
    "box jump": "Salto al cajón",
    "farmers walk": "Paseo del granjero (Farmers Walk)",
    "battle rope": "Entrenamiento con cuerdas de batalla (Battle Ropes)",
    "astride jumps": "Saltos laterales astride",
    "stationary bike run": "Pedaleo en bicicleta estática",
    "hands bike": "Pedaleo de manos (Bicicleta de brazos)",
    "assault airbike": "Bicicleta de aire (Assault Airbike)",
    "recumbent exercise bike": "Bicicleta estática reclinada",
    "ski step": "Paso de esquí (Ski Steps)",
    "skier gymstick": "Simulador de esquí con Gymstick",
    "the box jump": "Salto al cajón (Box Jump)",
    "box jump 1 to 2": "Salto de caja de 1 a 2 pies",
    "box jump 2 to 1": "Salto de caja de 2 a 1 pies",
    "single leg box jump": "Salto al cajón a una pierna",
    
    # BÍCEPS
    "barbell curl": "Curl de bíceps con barra",
    "dumbbell curl": "Curl de bíceps con mancuernas",
    "ez bar curl": "Curl de bíceps con barra EZ",
    "hammer curl": "Curl martillo",
    "preacher curl": "Curl predicador",
    "concentration curl": "Curl concentrado",
    "spider curl": "Curl araña",
    "waiter curl": "Curl de camarero",
    "cable curl": "Curl de bíceps en polea",
    "lying cable curl": "Curl de bíceps tumbado con polea",
    "seated hammer curl": "Curl martillo sentado",
    "seated alternating dumbbell curl": "Curl alterno con mancuernas sentado",
    "elbow flexion": "Flexión de codo (Glosario)",
    
    # TRÍCEPS
    "cable tricep kickback": "Patada de tríceps en polea",
    "dumbbell triceps extension": "Extensión de tríceps con mancuerna",
    "overhead triceps extension": "Extensión de tríceps tras nuca",
    "triceps pushdown": "Extensión de tríceps en polea",
    "ez bar lying triceps extension (skullcrusher)": "Press francés con barra EZ (Skullcrusher)",
    "parallel bar dips": "Fondos en paralelas",
    "dips between chairs": "Fondos entre bancos / sillas",
    "chair dips": "Fondos en silla",
    "assisted triceps dips": "Fondos asistidos en máquina",
    "triceps extension machine": "Extensión de tríceps en máquina",
    "bodyweight skull crushers": "Extensión de tríceps con peso corporal (Skullcrushers)",
    "reverse dips": "Fondos invertidos en banco",
    "ring dips": "Fondos en anillas",
    "korean dips": "Fondos coreanos (Korean Dips)",
    "straight bar dip": "Fondos en barra recta",
    "scapula dips": "Fondos escapulares",
    "impossible dips": "Fondos imposibles (Impossible Dips)",
    
    # ESPALDA
    "straight arm pulldown": "Pullover en polea alta",
    "straight-arm pulldown": "Pullover en polea alta",
    "lat pulldown": "Jalón al pecho",
    "behind the neck pulldown": "Jalón tras nuca",
    "seated cable row": "Remo en polea baja",
    "bent over row": "Remo inclinado con barra",
    "dumbbell row": "Remo con mancuerna",
    "one arm dumbbell row": "Remo unilateral con mancuerna",
    "t-bar row": "Remo con barra en T",
    "pull-up": "Dominadas prónas",
    "pullup": "Dominadas prónas",
    "chin-up": "Dominada supina",
    "chinup": "Dominada supina",
    "back extension": "Hiperextensiones lumbares",
    "hyperextension": "Hiperextensiones lumbares",
    "jumping pull-up": "Dominadas con salto",
    "ring inverted row": "Remo invertido en anillas",
    "shotgun row": "Remo unilateral en polea (Shotgun Row)",
    "inverted row": "Remo invertido (Dominadas australianas)",
    "weighted pull-up": "Dominadas con lastre",
    "front lever pull-up": "Dominadas en Front Lever",
    "neutral grip pull-up": "Dominadas con agarre neutro",
    "front lever": "Front Lever (Calistenia)",
    "back lever": "Back Lever (Calistenia)",
    "l-sit pull-up": "Dominadas en L-Sit",
    "scapula pull-up": "Dominadas escapulares",
    "behind the neck pull-up": "Dominadas tras nuca",
    "commando pull-up": "Dominadas de comando (Commando Pull-ups)",
    "isometric pull-up": "Dominada isométrica",
    "chin up around the bar": "Dominadas supinas alrededor de la barra",
    "bodyweight row in doorway": "Remo con peso corporal en marco de puerta",
    "lever high row": "Remo alto en máquina de palanca",
    "landmine t-bar row": "Remo con barra T en Landmine",
    "rack pull": "Peso muerto parcial (Rack Pulls)",
    "lever pullover": "Pullover en máquina de palanca",
    "lever reverse t-bar row": "Remo en barra T invertido en máquina",
    
    # PECHO
    "bench press": "Press de banca con barra",
    "dumbbell bench press": "Press de banca con mancuernas",
    "incline bench press": "Press de banca inclinado con barra",
    "incline dumbbell press": "Press inclinado con mancuernas",
    "decline bench press": "Press de banca declinado con barra",
    "decline dumbbell press": "Press declinado con mancuernas",
    "chest fly": "Aperturas de pecho con mancuernas",
    "push-up": "Flexión de pecho / lagartija",
    "pushup": "Flexión de pecho",
    "diamond push-up": "Flexión diamante",
    "cable crossover": "Cruce de poleas para pecho",
    "push-up to renegade row": "Flexiones con remo renegado",
    
    # HOMBROS
    "shoulder press": "Press de hombros con mancuernas",
    "military press": "Press militar con barra",
    "arnold press": "Press Arnold",
    "lateral raise": "Elevaciones laterales para hombros",
    "front raise": "Elevaciones frontales para hombros",
    "shrug": "Encogimiento de hombros",
    "face pull": "Face Pull en polea alta",
    "rear delt fly": "Pájaro / Vuelos posteriores en máquina",
    "bent over lateral raise": "Pájaro / Vuelos posteriores con mancuernas",
    "wall slides": "Deslizamientos en pared para hombros",
    "scapular protraction and retraction": "Protracción y retracción escapular",
    "shoulder pendulum": "Péndulo de hombro (Codman)",
    "shoulder external rotation": "Rotación externa de hombro",
    "shoulder internal rotation": "Rotación interna de hombro",
    "alternating shoulder flexion": "Flexión de hombro alterna con mancuerna",
    "wall supported arm raises": "Elevación de brazos apoyado en pared",
    "dead hang": "Colgado pasivo en barra (Dead Hang)",
    "backhand raise": "Elevación de dorso de la mano",
    "serratus wall slide with foam roller": "Deslizamientos en pared para serrato con rodillo",
    
    # PIERNAS
    "back squat": "Sentadilla trasera con barra",
    "front squat": "Sentadilla frontal con barra",
    "goblet squat": "Sentadilla Goblet",
    "bulgarian split squat": "Sentadilla búlgara con mancuernas",
    "leg press": "Prensa de piernas a 45 grados",
    "hack squat": "Sentadilla Hack en máquina",
    "seated leg curl": "Curl de piernas sentado",
    "lying leg curl": "Curl de piernas acostado / tumbado",
    "leg extension": "Extensión de piernas",
    "romanian deadlift": "Peso muerto rumano",
    "sumo deadlift": "Peso muerto sumo",
    "conventional deadlift": "Peso muerto convencional",
    "hip thrust": "Hip thrust con barra",
    "glute bridge": "Puente de glúteos",
    "glute bridge on bench": "Puente de glúteos apoyado en banco",
    "glute bridge one leg on bench": "Puente de glúteos a una pierna apoyado en banco",
    "unilateral bridge": "Puente de glúteos unilateral (a una pierna)",
    "side bridge hip abduction": "Plancha lateral con abducción de cadera",
    "frog pump": "Frog Pumps para glúteos",
    "fire hydrant": "Patada lateral de glúteo (Boca de incendio / Fire Hydrant)",
    "step up with knee raises": "Subidas al cajón con elevación de rodilla",
    "donkey kicks": "Patada de glúteo en cuadrupedia (Donkey Kicks)",
    "single leg hip thrust jump": "Salto con hip thrust a una pierna",
    "lateral leg swings": "Columpios laterales de piernas (Calentamiento)",
    "smith machine hip thrust": "Hip thrust en máquina Smith",
    "side hip abduction": "Abducción lateral de cadera",
    
    # PANTORRILLAS
    "calf raise": "Elevación de talones / pantorrillas",
    "standing calf raise": "Elevación de talones de pie",
    "seated calf raise": "Elevación de talones sentado",
    
    # ABDOMEN
    "plank": "Plancha abdominal",
    "side plank": "Plancha lateral",
    "crunch": "Crunch abdominal",
    "bicycle crunch": "Crunch bicicleta",
    "russian twist": "Giros rusos",
    "ab wheel rollout": "Rueda abdominal (Ab Wheel)",
    "hanging leg raise": "Elevación de piernas colgado",
    "lying leg raise": "Elevación de piernas acostado",
    "dead bug": "Bicho muerto (Dead Bug)",
    "4 point tummy vacuum exercise": "Vacío abdominal en 4 puntos (cuadrupedia)",
    "stomach vacuum": "Vacío abdominal de pie",
    "tummy vacuum": "Vacío abdominal",
    "abdominal bracing": "Activación isométrica abdominal (Bracing)",
    "abdominal hollow": "Vacío abdominal (Hollowing)",
    "bear crawl": "Caminata de oso (Bear Crawl)",
    "leg pull-in knee-ups": "Elevaciones de rodillas en banco sentado",
    "hanging knee raises": "Elevaciones de rodillas colgado",
    "dragon flag": "Dragon Flag (Abdominales de Dragón)",
    "high plank": "Plancha alta sobre manos",
    "ball russian twist throw with partner": "Lanzamiento de giros rusos con balón medicinal y compañero",
    "swing gymstick": "Giros con Gymstick",
    "down to up twist gymstick": "Giros de abajo a arriba con Gymstick",
    "bicycle crunch gymstick": "Abdominales bicicleta con Gymstick",
    "pelvic tilt": "Basculación / Inclinación pélvica",
    "reverse plank kicks": "Plancha invertida con patadas",
    "plank knee to elbow": "Plancha abdominal con rodilla al codo (Spiderman Plank)",
    "half wipers": "Medios limpiaparabrisas (Half Wipers)",
    "plank leg lift": "Plancha abdominal con elevación de pierna",
    "skater": "Saltos de patinador (Skaters)",
    "long arm crunch": "Crunch abdominal con brazos estirados",
    "jackknife sit-ups (v-up)": "Abdominales navaja (V-ups)",
    "flutter kick": "Aleteo de piernas (Flutter Kicks)",
    "hip abduction machine": "Abducciones de cadera en máquina",
    "side plank knee to elbow": "Plancha lateral con rodilla al codo",
    "suspended ab fall-out": "Despliegue de abdomen en suspensión (TRX)",
    "trx mountain climber": "Escaladores en suspensión con TRX",
    "half cross crunch": "Medio crunch cruzado (Abdominales)",
    "hip circles": "Círculos de cadera (Movilidad)",
    "side plank rotation": "Plancha lateral con rotación de tronco",
    "kicks leg bent": "Patadas con pierna flexionada",
    "hell slide": "Deslizamientos de talón en el suelo",
    "prone abdominal hollowing": "Vacío abdominal en prono (acostado boca abajo)",
    "rolling like a ball": "Rodar como una pelota (Pilates)",
    "hands in air dead bug": "Bicho muerto con manos arriba (Dead Bug)",
    "side plank oblique crunch": "Plancha lateral con crunch para oblicuos",
    "leg scissors": "Tijeras de piernas (Abdominales)",
    "side bent": "Flexión lateral de tronco de pie",
    "handstand": "Pino de pie (Handstand)",
    "handstand walk": "Caminata sobre manos (Handstand Walk)",
    "climbing monkey bars": "Pasamanos (Climbing Monkey Bars)",
    "supine spinal twist": "Giro espinal en supino (Estiramiento)",
    "plank jacks / extended leg": "Plancha con saltos de pies (Plank Jacks)",
    
    # OTROS / MASAJES / MOVILIDAD
    "foam roller posterior shoulder": "Masaje de hombro posterior con rodillo de espuma (Foam Roller)",
    "foam roller rhomboids": "Masaje de romboides con rodillo de espuma (Foam Roller)",
    "foam roller glutes": "Masaje de glúteos con rodillo de espuma (Foam Roller)",
    "foam roller quads": "Masaje de cuádriceps con rodillo de espuma (Foam Roller)",
    "foam roller upper back": "Masaje de espalda alta con rodillo de espuma (Foam Roller)",
    "foam roller plantar fasciitis": "Masaje de planta del pie con rodillo de espuma / pelota",
    "foam roller hamstrings": "Masaje de isquiotibiales con rodillo de espuma (Foam Roller)",
    "foam roller front shoulder and chest": "Masaje de hombro frontal y pectoral con rodillo",
    "foam roller calves": "Masaje de pantorrillas con rodillo de espuma (Foam Roller)",
    "reaction ball throw": "Lanzamiento con pelota de reacción",
    "vibration plate": "Ejercicio en plataforma vibratoria",
    "duck walk": "Caminata de pato (Duck Walk)",
    "swing 360": "Giro 360 con pesa rusa / barra",
    "1-2 stick drill": "Paso lateral 1-2 (Coordinación)",
    "knee circles": "Círculos de rodillas (Movilidad)",
    "hip circles": "Círculos de cadera (Movilidad)",
    "foot and ankle rotation": "Rotación de pie y tobillo (Movilidad)",
    "chaturanga dandasana": "Postura de plancha baja (Chaturanga Dandasana)",
    "double leg stretch": "Estiramiento de doble pierna (Pilates)",
    "single knee to chest": "Estiramiento de rodilla al pecho",
    "snap jumps": "Saltos snap (Snap Jumps / Medio Burpee)",
    "depth jump to hurdle hop": "Salto de profundidad a salto de valla (Pliometría)",
}

with open(json_path, "r", encoding="utf-8") as f:
    data = json.load(f)

updated = 0
for key, val in data.items():
    # Normalizar
    name_en = val.get("name_en", "").strip().lower()
    name_en = name_en.replace("-", " ").replace("|", " ")
    name_en = re.sub(r'\s+', ' ', name_en).strip()
    
    # Evaluar contra el mapeo consolidado
    if name_en in mapeo_consolidado:
        old_val = val.get("name_es", "")
        new_val = mapeo_consolidado[name_en]
        if old_val != new_val:
            val["name_es"] = new_val
            updated += 1
            print(f"Modificado: '{name_en}' -> '{new_val}'")

if updated > 0:
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Éxito. Se modificaron y guardaron {updated} ejercicios en {out_path}.")
else:
    print("No se encontraron diferencias para modificar.")
